.Dd $Mdocdate: July 16 2013 $
.Dt ZONE 8
.Os
.Sh NAME
.Nm zone
.Nd manage the container technology provided by zones
.Sh SYNOPSIS
.Nm zone
.Op create|destroy|list|exec
.Op zonename|zonename/zoneid|_|zonename/zoneid program [arg ...]
.Sh DESCRIPTION
The
.Nm
utility provides managment of the zone technology 
and allows creation, destruction or viewing of 
the container zones. 
